Add nock types to work around broken dependency config
Currently we're getting the error

  node_modules/fancy-test/lib/types.d.ts(3,23): error TS2307: Cannot find module 'nock' or its corresponding type declarations.

because fancy-test is implicitly depending on nock (see
https://github.com/oclif/fancy-test/issues/42 ). For now,
just add nock as a dev dependency ourselves.